package com.store.entities;


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Bank generated by hbm2java
 */
@Entity
@Table(name="bank"
    ,catalog="ecommerce"
)
public class Bank  implements java.io.Serializable {


     private BankId id;

    public Bank() {
    }

    public Bank(BankId id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="creditCardId", column=@Column(name="credit_card_id", nullable=false) ), 
        @AttributeOverride(name="balance", column=@Column(name="balance", length=255) ), 
        @AttributeOverride(name="creditCardNumber", column=@Column(name="credit_card_number", nullable=false, length=45) ), 
        @AttributeOverride(name="cvv", column=@Column(name="CVV", nullable=false, length=3) ) } )
    public BankId getId() {
        return this.id;
    }
    
    public void setId(BankId id) {
        this.id = id;
    }




}


