package com.store.entities;


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Subcategory generated by hbm2java
 */
@Entity
@Table(name="subcategory"
    ,catalog="ecommerce"
)
public class Subcategory  implements java.io.Serializable {


     private int id;
     private Category category;
     private String name;
     private Set<Product> products = new HashSet<Product>(0);

    public Subcategory() {
    }

	
    public Subcategory(int id, Category category, String name) {
        this.id = id;
        this.category = category;
        this.name = name;
    }
    public Subcategory(int id, Category category, String name, Set<Product> products) {
       this.id = id;
       this.category = category;
       this.name = name;
       this.products = products;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="category_id", nullable=false)
    public Category getCategory() {
        return this.category;
    }
    
    public void setCategory(Category category) {
        this.category = category;
    }

    
    @Column(name="name", nullable=false, length=255)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="subcategory")
    public Set<Product> getProducts() {
        return this.products;
    }
    
    public void setProducts(Set<Product> products) {
        this.products = products;
    }




}


