package com.store.entities;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Token generated by hbm2java
 */
@Entity
@Table(name="token"
    ,catalog="ecommerce"
)
public class Token  implements java.io.Serializable {


     private int tokenId;
     private String token;

    public Token() {
    }

    public Token(int tokenId, String token) {
       this.tokenId = tokenId;
       this.token = token;
    }
   
     @Id 

    
    @Column(name="token_id", unique=true, nullable=false)
    public int getTokenId() {
        return this.tokenId;
    }
    
    public void setTokenId(int tokenId) {
        this.tokenId = tokenId;
    }

    
    @Column(name="token", nullable=false, length=255)
    public String getToken() {
        return this.token;
    }
    
    public void setToken(String token) {
        this.token = token;
    }




}


