package com.store.db.domain;// default package
// Generated Jun 5, 2021, 12:33:40 AM by Hibernate Tools 6.0.0.Alpha2


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * OrderItem generated by hbm2java
 */
@Entity
@Table(name="order_item"
    ,catalog="ecommerce"
)
public class OrderItem  implements java.io.Serializable {


     private int id;
     private Product product;
     private Order order;
     private int prodId;
     private int quantity;
     private double unitPrice;
     private Set<SoldItem> soldItems = new HashSet<SoldItem>(0);

    public OrderItem() {
    }

	
    public OrderItem(int id, Product product, Order order, int prodId, int quantity, double unitPrice) {
        this.id = id;
        this.product = product;
        this.order = order;
        this.prodId = prodId;
        this.quantity = quantity;
        this.unitPrice = unitPrice;
    }
    public OrderItem(int id, Product product, Order order, int prodId, int quantity, double unitPrice, Set<SoldItem> soldItems) {
       this.id = id;
       this.product = product;
       this.order = order;
       this.prodId = prodId;
       this.quantity = quantity;
       this.unitPrice = unitPrice;
       this.soldItems = soldItems;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="product_id", nullable=false)
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="order_id", nullable=false)
    public Order getOrder() {
        return this.order;
    }
    
    public void setOrder(Order order) {
        this.order = order;
    }

    
    @Column(name="prod_id", nullable=false)
    public int getProdId() {
        return this.prodId;
    }
    
    public void setProdId(int prodId) {
        this.prodId = prodId;
    }

    
    @Column(name="quantity", nullable=false)
    public int getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }

    
    @Column(name="unit_price", nullable=false, precision=22, scale=0)
    public double getUnitPrice() {
        return this.unitPrice;
    }
    
    public void setUnitPrice(double unitPrice) {
        this.unitPrice = unitPrice;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="orderItem")
    public Set<SoldItem> getSoldItems() {
        return this.soldItems;
    }
    
    public void setSoldItems(Set<SoldItem> soldItems) {
        this.soldItems = soldItems;
    }




}


