package com.store.model;


import javax.persistence.*;

/**
 * BankAccount generated by hbm2java
 */
@Entity
@Table(name = "bank"
        , catalog = "ecommerce"
)
public class BankAccount implements java.io.Serializable {

    @Column(name = "id")
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer id;
    @Column(name = "balance")
    private Double balance;
    @Column(name = "credit_card_number")
    private String creditCardNumber;
    @Column(name = "cvv")
    private String cvv;

    public BankAccount() {
    }

    public BankAccount(Integer id, Double balance, String creditCardNumber, String cvv) {
        this.balance = balance;
        this.creditCardNumber = creditCardNumber;
        this.cvv = cvv;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Double getBalance() {
        return balance;
    }

    public void setBalance(Double balance) {
        this.balance = balance;
    }

    public String getCreditCardNumber() {
        return creditCardNumber;
    }

    public void setCreditCardNumber(String creditCardNumber) {
        this.creditCardNumber = creditCardNumber;
    }

    public String getCvv() {
        return cvv;
    }

    public void setCvv(String cvv) {
        this.cvv = cvv;
    }

    @Override
    public String toString() {
        return "BankAccount{" +
                "id=" + id +
                ", balance=" + balance +
                ", creditCardNumber='" + creditCardNumber + '\'' +
                ", cvv='" + cvv + '\'' +
                '}';
    }
}


