package com.store.model;


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * BankId generated by hbm2java
 */
@Embeddable
public class BankId  implements java.io.Serializable {


     private int creditCardId;
     private String balance;
     private String creditCardNumber;
     private String cvv;

    public BankId() {
    }

	
    public BankId(int creditCardId, String creditCardNumber, String cvv) {
        this.creditCardId = creditCardId;
        this.creditCardNumber = creditCardNumber;
        this.cvv = cvv;
    }
    public BankId(int creditCardId, String balance, String creditCardNumber, String cvv) {
       this.creditCardId = creditCardId;
       this.balance = balance;
       this.creditCardNumber = creditCardNumber;
       this.cvv = cvv;
    }
   


    @Column(name="credit_card_id", nullable=false)
    public int getCreditCardId() {
        return this.creditCardId;
    }
    
    public void setCreditCardId(int creditCardId) {
        this.creditCardId = creditCardId;
    }


    @Column(name="balance", length=255)
    public String getBalance() {
        return this.balance;
    }
    
    public void setBalance(String balance) {
        this.balance = balance;
    }


    @Column(name="credit_card_number", nullable=false, length=45)
    public String getCreditCardNumber() {
        return this.creditCardNumber;
    }
    
    public void setCreditCardNumber(String creditCardNumber) {
        this.creditCardNumber = creditCardNumber;
    }


    @Column(name="CVV", nullable=false, length=3)
    public String getCvv() {
        return this.cvv;
    }
    
    public void setCvv(String cvv) {
        this.cvv = cvv;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof BankId) ) return false;
		 BankId castOther = ( BankId ) other; 
         
		 return (this.getCreditCardId()==castOther.getCreditCardId())
 && ( (this.getBalance()==castOther.getBalance()) || ( this.getBalance()!=null && castOther.getBalance()!=null && this.getBalance().equals(castOther.getBalance()) ) )
 && ( (this.getCreditCardNumber()==castOther.getCreditCardNumber()) || ( this.getCreditCardNumber()!=null && castOther.getCreditCardNumber()!=null && this.getCreditCardNumber().equals(castOther.getCreditCardNumber()) ) )
 && ( (this.getCvv()==castOther.getCvv()) || ( this.getCvv()!=null && castOther.getCvv()!=null && this.getCvv().equals(castOther.getCvv()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getCreditCardId();
         result = 37 * result + ( getBalance() == null ? 0 : this.getBalance().hashCode() );
         result = 37 * result + ( getCreditCardNumber() == null ? 0 : this.getCreditCardNumber().hashCode() );
         result = 37 * result + ( getCvv() == null ? 0 : this.getCvv().hashCode() );
         return result;
   }   


}


