package com.store.model;// default package
// Generated Jun 5, 2021, 12:33:40 AM by Hibernate Tools 6.0.0.Alpha2


import javax.persistence.*;
import java.util.Date;

/**
 * Review generated by hbm2java
 */
@Entity
@Table(name="review"
    ,catalog="ecommerce"
)
public class Review  implements java.io.Serializable {


     private int id;
     private Product product;
     private User user;
     private Date createdAt;
     private int rating;
     private String reviewText;

    public Review() {
    }

	
    public Review(int id, Product product, User user, Date createdAt, int rating) {
        this.id = id;
        this.product = product;
        this.user = user;
        this.createdAt = createdAt;
        this.rating = rating;
    }
    public Review(int id, Product product, User user, Date createdAt, int rating, String reviewText) {
       this.id = id;
       this.product = product;
       this.user = user;
       this.createdAt = createdAt;
       this.rating = rating;
       this.reviewText = reviewText;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="product_id", nullable=false)
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="customer_id", nullable=false)
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="createdAt", nullable=false, length=19)
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    
    @Column(name="rating", nullable=false)
    public int getRating() {
        return this.rating;
    }
    
    public void setRating(int rating) {
        this.rating = rating;
    }

    
    @Column(name="review_text", length=250)
    public String getReviewText() {
        return this.reviewText;
    }
    
    public void setReviewText(String reviewText) {
        this.reviewText = reviewText;
    }




}


